# -*- coding: utf-8 -*-
"""Hotel Billing Programme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6F8mColevC10ugmoF7IVcoaONoyvGWq
"""

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

guests[0]

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

guests[0]

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

print (guests[1]['name'])
print (guests[2]['days'])
print (guests[2]['room'])
print (guests[1]['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

print (guests[0]['name'])
print (guests[0]['days'])
print (guests[0]['room'])
print (guests[0]['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

(guests[-4]['name'])
(guests[-4]['days'])
(guests[-4]['room'])
(guests[-4]['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
  print (guest)

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

guest ['name']

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
  print (guest['name'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
  print(guest['name'], guest['days'], guest['room'], guest['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
  print ('name',guest['name'], 'days',guest['days'], 'room',guest ['room'], 'food',guest['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
    print('name', guest['name'],
          'days', guest['days'],
          'room', guest['room'],
          'food', guest['food'])

guests = [
    {"name": "Rahul", "days": 3, "room": 2500, "food": 1200},
    {"name": "Priya", "days": 5, "room": 3000, "food": 1800},
    {"name": "Amit", "days": 2, "room": 2000, "food": 900},
    {"name": "Sneha", "days": 7, "room": 3500, "food": 2500}
]

for guest in guests:
  guest ['total'] = (guest['room'] + guest['food']) * guest ['days']
for guest in guests:
  print (guest['name'],guest ['total'])
grand_total = 0
for guest in guests:
  grand_total = grand_total + guest ['total']
print ('Grand Total:', grand_total)

average = grand_total /len(guests)
print ('Average:', round(average,2))

highest = 0
highest_guest=''

for guest in guests:
  if guest['total'] > highest:
    highest = guest['total']
    highest_guest =guest['name']
print ('Highest:',   highest_guest, highest )

guests = [
    {'name': 'Rahul', 'days':3, 'room':2500, 'food':1100},
    {'name': 'Priya', 'days':5, 'room':3000, 'food':1800},
    {'name': 'Amit', 'days':2, 'room':2000, 'food':900},
    {'name': 'Sneha', 'days':7, 'room':3500, 'food':2500},
]

#Guest's Individual Totals

for guest in guests:
  guest ['total'] = (guest['room'] + guest ['food']) * guest ['days']
  print (guest['name'], round(guest['total'],2))

print ()

#Guest's Individual Taxes

tax_rate = 0.10
for guest in guests:
  guest['tax'] = guest ['total'] * tax_rate
  print (guest['name'], guest['tax'])

print ()

#Individual Guest's Grand Total

for guest in guests:
  guest['final_bill']=  guest ['total'] + guest['tax']
  print (guest['name'],  round(guest['final_bill'],2))

print ()

#Grand Total (Amount of all guests)

grand_total = 0

for guest in guests:
    grand_total = grand_total + guest['final_bill']

print('Grand Total:', round(grand_total,2))

#Average Billing

average_billing = grand_total / len(guests)
print ('Average Billing:', round(average_billing,2))

